#!/bin/bash

echo "==================================="
echo "Aerilux Website - Installation Guide"
echo "==================================="
echo ""
echo "Due to npm permission issues, please run the following commands manually:"
echo ""
echo "1. Fix npm permissions (run once):"
echo "   sudo chown -R $(whoami) ~/.npm"
echo ""
echo "2. Install dependencies:"
echo "   npm install"
echo ""
echo "3. Start the development server:"
echo "   npm start"
echo ""
echo "The website will open automatically at http://localhost:3000"
echo ""
echo "==================================="
echo "Backend API Information:"
echo "==================================="
echo ""
echo "The frontend is prepared to connect to a backend API at:"
echo "- Development: http://localhost:3001/api"
echo "- Production: Set REACT_APP_API_URL environment variable"
echo ""
echo "Backend endpoints prepared:"
echo "- Products management"
echo "- Order processing"
echo "- Inventory tracking"
echo "- Payment processing"
echo "- User management"
echo ""
echo "===================================" 